---

provisioner:
  name: chef_zero
  require_chef_omnibus: true

driver:
  name: vagrant

platforms:
- name: centos-6.4
- name: ubuntu-12.04

suites:
- name: default
  run_list:
    - recipe[ktc-etcd::setup]
  attributes:
    ha_disabled: true
    etcd:
      servers:
        - 127.0.0.1
